### ISSUE TITLE
How to execute?

### ISSUE THREAD

**Issue by the-REAL-beautysleep** [catabriga/graphwar#7]
Downloaded this from http://www.graphwar.com/ as the .jar file http://www.graphwar.com/graphwar.jar:
When I open it,  it just opens as a folder to be extracted

https://user-images.githubusercontent.com/72076180/155342151-b652f831-e3ce-4759-aded-408a517f4b04.mp4

system: ubuntu 20.04

I also tried

`$ cd Downloads

 $ java -jar ./graphwar.jar XXX.XXX.XXX.XXX

Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't load library: /usr/lib/jvm/java-11-openjdk-amd64/lib/libawt_xawt.so
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2630)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1837)
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2648)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
	at java.base/java.lang.System.loadLibrary(System.java:1873)
	at java.desktop/java.awt.Toolkit$3.run(Toolkit.java:1399)
	at java.desktop/java.awt.Toolkit$3.run(Toolkit.java:1397)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/java.awt.Toolkit.loadLibraries(Toolkit.java:1396)
	at java.desktop/java.awt.Toolkit.<clinit>(Toolkit.java:1429)
	at java.desktop/java.awt.Component.<clinit>(Component.java:621)
`

**Comment by germangb** [comment]
Do you have `/usr/lib/jvm/java-11-openjdk-amd64/lib/libawt_xawt.so`?

**Comment by the-REAL-beautysleep** [comment]
I didn't at the time, just installed [it](https://exerror.com/exception-java-lang-unsatisfiedlinkerror-cant-load-library-usr-lib-jvm-java-11-openjdk-amd64-lib-libawt_xawt-so/) there.
```sudo apt install openjdk-11-jdk``` 

now I get 
"Downloads/graphwar.jar' is not marked as executable.  If this was downloaded or copied from an untrusted source, it may be dangerous to run.  For more details, read about the executable bit."

so I did the following, with success

on terminal 
```
git clone git@github.com:catabriga/graphwar.git

cd graphwar

make

java -jar graphwar.jar
```
all works perfectly so far, thank you !
